version: "3"
services:
  restaurant_backend:
    image: backend_restaurant:develop
    container_name: "FlaskRestauranDevelop"
    env_file: .env
    ports:
      - "9000:9000"
    volumes: 
      - ./project_flask/flasky:/home/desarrollo
    command: /bin/bash -c "
              sleep 5;  
              python3 manage.py runserver -h 0.0.0.0 -p 9000 -r -d"
  
  restaurant_db:
    container_name: "PostgresDevelop"
    env_file: .env
    volumes:
      - data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    
volumes:
  data:
    driver: local

