version: "2.0"
services:
  backend:
    build:
      context: ./project_flask
    container_name: "flask_restaurant"
    env_file: .env
    ports:
      - "9000:9000"
    volumes: 
      - ./project_flask/flasky:/home/desarrollo
    command: /bin/bash -c "
              sleep 5;  
              python manage.py runserver -h 0.0.0.0 -p 9000"
    links: 
      - db
    networks:
      app_net:
        ipv4_address: '$FLASK_IP'

  db:
    image: postgres:9.5.6
    container_name: "db_restaurant"
    env_file: .env
    ports: 
      - "5432:5432"
    expose:
      - "5432"
    networks:
      app_net:
        ipv4_address: '$POSTGRES_IP'
    


networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.5.0/24