version: "2.0"
services:
  backend:
    image: devjulian/app-restaurant-udacity
    container_name: "flask_restaurant"
    ports:
      - "9000:9000"
    volumes: 
      - home/desarrollo
    command: /bin/bash -c "
              sleep 5;  
              python app.py"
    depends_on: 
      - db

  db:
    image: postgres:9.5.6
    container_name: "db_restaurant"
    env_file: .env
    ports: 
      - "5432:5432"
    expose:
      - "5432"
    

      