version: "2.0"
services:
  backend:
    image: devjulian/app-restaurant-udacity:latest
    container_name: "flask_restaurant"
    ports:
      - "9000:9000"
    command: /bin/bash -c "
              sleep 5;  
              python3 manage.py runserver -h 0.0.0.0 -p 9000 -r -d"
    links: 
      - db
    networks:
      app_net:
        ipv4_address: '$FLASK_IP'

  db:
    image: postgres:9.5.6
    container_name: "db_restaurant"
    env_file: .env
    ports: 
      - "5432:5432"
    expose:
      - "5432"
    volumes_from:
      - pg_data
    networks:
      app_net:
        ipv4_address: '$POSTGRES_IP'
    
  pg_data:
    build:
      context: ./pg_data
    container_name: persistence_app_restaurant

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.5.0/24