version: '2'
services:
  backend_testing:
    build:
      context: ./project_flask
    container_name: "flask_restaurant_testing"
    env_file: .env
    volumes: 
      - ./project_flask/flasky:/home/desarrollo
    command: /bin/bash -c "
              sleep 5;  
              python3 -u -m app.test"
    networks:
      app_net:
        ipv4_address: '$FLASK_IP_TEST'

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.5.0/24