"""empty message

Revision ID: 03401af7ea65
Revises: 20d7b841a6ea
Create Date: 2017-07-20 19:05:42.539823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03401af7ea65'
down_revision = '20d7b841a6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('user_name', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'user', ['user_name'])
    op.drop_column('user', 'token')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_name')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
