"""empty message

Revision ID: 129f7df1ac79
Revises: 1107a8e85f18
Create Date: 2017-07-16 21:49:16.280296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129f7df1ac79'
down_revision = '1107a8e85f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_meal_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_proposal', sa.Integer(), nullable=True),
    sa.Column('meal_date_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_meal_date')
    # ### end Alembic commands ###
