"""empty message

Revision ID: 1f09c8d2ec8b
Revises: 9595ed8add12
Create Date: 2017-06-25 23:50:52.996524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f09c8d2ec8b'
down_revision = '9595ed8add12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('proposal', sa.Column('user_proposed_from', sa.Integer(), nullable=True))
    op.drop_constraint('proposal_request_id_fkey', 'proposal', type_='foreignkey')
    op.create_foreign_key(None, 'proposal', 'request', ['user_id'], ['id'])
    op.drop_column('proposal', 'request_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'proposal', type_='foreignkey')
    op.create_foreign_key('proposal_request_id_fkey', 'proposal', 'request', ['request_id'], ['id'])
    op.drop_column('proposal', 'user_proposed_from')
    op.drop_column('proposal', 'user_id')
    # ### end Alembic commands ###
