"""empty message

Revision ID: 20d7b841a6ea
Revises: 7520ff9918df
Create Date: 2017-07-17 00:02:37.773389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d7b841a6ea'
down_revision = '7520ff9918df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_meal_date')
    op.add_column('mealdate', sa.Column('user_id_proposal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mealdate', 'user_id_proposal')
    op.create_table('users_meal_date',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id_proposal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('meal_date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['meal_date_id'], ['mealdate.id'], name='users_meal_date_meal_date_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_meal_date_pkey')
    )
    # ### end Alembic commands ###
