"""empty message

Revision ID: 50099488865a
Revises: 
Create Date: 2017-07-24 05:00:19.572159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50099488865a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mealdate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_request', sa.Integer(), nullable=True),
    sa.Column('user_id_proposal', sa.Integer(), nullable=True),
    sa.Column('restaurant_name', sa.String(length=100), nullable=False),
    sa.Column('restaurant_address', sa.String(length=100), nullable=False),
    sa.Column('restaurant_picture', sa.String(length=100), nullable=False),
    sa.Column('meal_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meal_type', sa.String(length=100), nullable=False),
    sa.Column('location_request', sa.String(length=100), nullable=False),
    sa.Column('latitud', sa.String(length=100), nullable=False),
    sa.Column('meal_time', sa.DateTime(), nullable=False),
    sa.Column('filled', sa.Boolean(), nullable=True),
    sa.Column('filled_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('user_proposed_to', sa.Integer(), nullable=True),
    sa.Column('user_proposed_from', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal')
    op.drop_table('request')
    op.drop_table('user')
    op.drop_table('mealdate')
    # ### end Alembic commands ###
