"""empty message

Revision ID: 53ce7b082ce1
Revises: c04b8e3d9ee9
Create Date: 2017-06-26 00:16:44.826221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ce7b082ce1'
down_revision = 'c04b8e3d9ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('proposal_user_proposed_to_fkey', 'proposal', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('proposal_user_proposed_to_fkey', 'proposal', 'user', ['user_proposed_to'], ['id'])
    # ### end Alembic commands ###
