"""empty message

Revision ID: 7520ff9918df
Revises: cddac612f703
Create Date: 2017-07-16 22:01:52.097859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7520ff9918df'
down_revision = 'cddac612f703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users_meal_date', 'mealdate', ['meal_date_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_meal_date', type_='foreignkey')
    # ### end Alembic commands ###
