"""empty message

Revision ID: 86dd31af6d59
Revises: 53ce7b082ce1
Create Date: 2017-06-26 00:21:41.087984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86dd31af6d59'
down_revision = '53ce7b082ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mealdate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_request', sa.Integer(), nullable=True),
    sa.Column('users_ids', sa.Integer(), nullable=True),
    sa.Column('restaurant_name', sa.String(length=100), nullable=False),
    sa.Column('restaurant_address', sa.String(length=100), nullable=False),
    sa.Column('restaurant_picture', sa.String(length=100), nullable=False),
    sa.Column('meal_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mealdate')
    # ### end Alembic commands ###
