"""empty message

Revision ID: 9595ed8add12
Revises: 09ef843206fb
Create Date: 2017-06-25 23:04:06.931479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9595ed8add12'
down_revision = '09ef843206fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_proposed_to', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['user_proposed_to'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal')
    # ### end Alembic commands ###
