"""empty message

Revision ID: c04b8e3d9ee9
Revises: 1f09c8d2ec8b
Create Date: 2017-06-26 00:11:51.960706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04b8e3d9ee9'
down_revision = '1f09c8d2ec8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('request_id', sa.Integer(), nullable=True))
    op.drop_constraint('proposal_user_id_fkey', 'proposal', type_='foreignkey')
    op.create_foreign_key(None, 'proposal', 'request', ['request_id'], ['id'])
    op.drop_column('proposal', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'proposal', type_='foreignkey')
    op.create_foreign_key('proposal_user_id_fkey', 'proposal', 'request', ['user_id'], ['id'])
    op.drop_column('proposal', 'request_id')
    # ### end Alembic commands ###
