"""empty message

Revision ID: cddac612f703
Revises: 129f7df1ac79
Create Date: 2017-07-16 21:50:00.966370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cddac612f703'
down_revision = '129f7df1ac79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mealdate', 'users_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mealdate', sa.Column('users_ids', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
